export const SEARCH_FOCUS = 'header/search_focus'
export const SEARCH_BLUR = 'header/search_blur'
export const SET_HOT_LIST = 'header/set_hot_list'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE ='header/mouse_leave'
